$color             = rgba(26, 21, 21, 1.0)
$inner_color       = rgba(23, 18, 18, 0.72)
$outer_color       = rgba(69, 54, 54, 1.0)
$outer_color_focus = rgba(227, 156, 69, 1.0)
$font_color        = rgba(220, 201, 188, 1.0)
$placeholder_color = rgba(156, 129, 129, 0.78)
$check_color       = rgba(117, 109, 148, 1.0)
$fail_color        = rgba(207, 34, 62, 1.0)

background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 4
    noise = 0.011
    contrast = 1.0
    brightness = 0.92
    vibrancy = 0.10
    vibrancy_darkness = 0.0
}

general {
    hide_cursor = true
    grace = 0
    no_fade_in = false
}

input-field {
    monitor =
    size = 280, 56
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.22
    dots_center = true
    outer_color = $outer_color
    inner_color = $inner_color
    font_color = $font_color
    fade_on_empty = false
    placeholder_text = <span foreground="##9C8181">Password...</span>
    hide_input = false
    check_color = $check_color
    fail_color = $fail_color
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = rgba(227, 156, 69, 1.0)
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%I:%M')"
    color = $font_color
    font_size = 92
    font_family = Liberation Sans
    position = 0, 90
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%A, %B %-d')"
    color = rgba(156, 129, 129, 1.0)
    font_size = 22
    font_family = Liberation Sans
    position = 0, 20
    halign = center
    valign = center
}
