# This file is intended to be included in your main hyprland.conf.

$activeBorderColor   = rgb(E39C45) rgb(AE3F82) rgb(756D94) rgb(E39C45) 35deg
$inactiveBorderColor = rgba(453636cc)
$groupActiveColor    = rgb(E39C45) rgb(CF223E) rgb(7B3D79) rgb(E39C45) 35deg
$groupInactiveColor  = rgba(2D2424cc)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $groupActiveColor
    col.border_inactive = $groupInactiveColor
    groupbar {
        text_color = rgb(DCC9BC)
        col.active = rgb(3E3030)
        col.inactive = rgb(171212)
        col.locked_active = rgb(CF223E)
        col.locked_inactive = rgb(453636)
    }
}

decoration {
    rounding = 10

    blur {
        enabled = true
        size = 3
        passes = 2
        noise = 0.01
        contrast = 1.0
        brightness = 0.95
        vibrancy = 0.08
    }

    shadow {
        enabled = true
        range = 10
        render_power = 3
        color = rgba(00000055)
    }
}
